name: Testing

on: [pull_request]

# Set the name of the sppkg file
env:
  SPPKG_FILE_NAME: 'spfx-cicd.sppkg'
  SEND_MAIL: 'true'

jobs:
  
  deploy-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v1
        
    # Login to tenant using action-cli-login
    - name: Office 365 CLI Login
      uses: anoopt/action-cli-login@master
      with:
        ADMIN_USERNAME:  ${{ secrets.adminUsername }}
        ADMIN_PASSWORD:  ${{ secrets.adminPassword }}
        
    # Run script bash
    - name: Office 365 CLI Runscript bash
      uses: anoopt/action-cli-runscript@master
      with:
        O365_CLI_SCRIPT_PATH: './scripts/appcatalog.sh'
        
    # Run script PS
    - name: Office 365 CLI Runscript PS
      uses: anoopt/action-cli-runscript@master
      with:
        O365_CLI_SCRIPT_PATH: './scripts/appcatalog.ps1' 
  
