name: Testing CLI Actions

on: [pull_request]

jobs:
  runscript-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v1          
    
    # Login to tenant using action-cli-login
    - name: Office 365 CLI Login
      uses: anoopt/o365-cli-actions-test/login@master
      env:
        ADMIN_USERNAME:  ${{ secrets.adminUsername }}
        ADMIN_PASSWORD:  ${{ secrets.adminPassword }}
        
    # Send an email using action-cli-runscript
    - name: Office 365 CLI Send email
      uses: anoopt/o365-cli-actions-test/runscript@master
      env:
        APP_ID: 123
        O365_CLI_SCRIPT_PATH: /scripts/mail.sh
